language: objective-c
osx_image: xcode10.1

script:
  - set -o pipefail
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXCore clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXCoreBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXRuntime clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXRuntimeBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXJson clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXJsonBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXLayout clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXLayoutBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXData clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXDataBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXWidget clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXWidgetBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXNetwork clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXNetworkBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXGcode clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXGcodeBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXWidgetGcode clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXWidgetGcodeBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXZip clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace AGXToolkit.xcworkspace -scheme AGXZipBuilder clean build archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
