language: objective-c
osx_image: xcode10.1
xcode_workspace: AGXToolkit.xcworkspace
xcode_scheme:
  - AGXCoreTest
  - AGXRuntimeTest
  - AGXJsonTest
  - AGXDataTest
  - AGXNetworkTest
  - AGXGcodeTest
  - AGXZipTest
