language: objective-c
osx_image: xcode10.1
xcode_workspace: AGXToolkit.xcworkspace
xcode_scheme:
  - AGXCore
  - AGXRuntime
  - AGXJson
  - AGXLayout
  - AGXData
  - AGXWidget
  - AGXNetwork
  - AGXGcode
  - AGXWidgetGcode
  - AGXZip
